### ISSUE TITLE
 Preview of the content with the AmppStar logo* when sharing on other SM sites

### ISSUE THREAD

**Issue by BisoMandic** [eliataylor/ampp-keystone#11]
I tested sharing the content on FB and the functionality works well which is awesome but it'd be nice to have a picture preview of the content with the Amppstar logo on the side (see attached screenshots).

Current:
![2017-09-23_1544](https://user-images.githubusercontent.com/32228117/30777444-e7275644-a077-11e7-94f1-47b812ec1d72.png)

Suggested:
![2017-09-23_1552](https://user-images.githubusercontent.com/32228117/30777445-f56977f0-a077-11e7-9259-d4597086140b.png)

or

![2017-09-23_1557](https://user-images.githubusercontent.com/32228117/30777446-f56dd4bc-a077-11e7-951b-f7561bb649d0.png)

**Comment by eliataylor** [comment]
fixed.

![screen shot 2017-09-27 at 8 28 33 pm](https://user-images.githubusercontent.com/6335974/30948090-79a869a2-a3c2-11e7-8533-91e0b20cc77a.png)

**Comment by BisoMandic** [comment]
Awesome!!! :D

**Comment by BisoMandic** [comment]
I have to reopen this one since it seems to only work for the music and poetry mediums but not the art and photography (see screenshots below of the ones which work and then the ones which don't).

![2017-09-28_1844_001](https://user-images.githubusercontent.com/32228117/30996334-66aac9a6-a47d-11e7-8469-5b6eb537ab27.png)
![2017-09-28_1845](https://user-images.githubusercontent.com/32228117/30996335-66b03346-a47d-11e7-8fd4-d509784040f5.png)

![2017-09-28_1843](https://user-images.githubusercontent.com/32228117/30996343-76f5df08-a47d-11e7-80cf-8b8cd58d3858.png)
![2017-09-28_1844](https://user-images.githubusercontent.com/32228117/30996344-76f9c172-a47d-11e7-87d1-7c7f97126c5f.png)

**Comment by eliataylor** [comment]
i've cleared the FB cache on Baskin (https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fafternoon-mesa-52732.herokuapp.com%2Fart%2F59a4c5e5f009460004fb0a5d). 

This might need to be done to all URLs that have tried to be shared before this fix was in place

**Comment by BisoMandic** [comment]
This still does not seem to be working and a preview of the content would definitely be nice.
![2017-10-24_2116](https://user-images.githubusercontent.com/32228117/31978834-968b446a-b900-11e7-8524-35ad6bc25120.png)

**Comment by eliataylor** [comment]
always test this at least twice. and consider clearing FB cache if it persists.
